# Generated by Django 4.2.5 on 2026-02-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.IntegerField()),
                ('avc', models.FloatField()),
                ('itm', models.IntegerField()),
                ('inc', models.FloatField()),
                ('hpp', models.FloatField()),
                ('prf', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'closing',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.DeleteModel(
            name='Close',
        ),
    ]
